>P1;3rze
structureX:3rze:28:A:485:A::::
MSLPNS---SCLLEDKMCEGNKTTMASPQLMPLVVVLSTICLVTVGLNLLVLYAVRSERK
LHTVGNLYIVSLSVADLIVGAVVMPMNILYLLMSKWSLGRPLCLFWLSMDYVASTASIFS
VFILCIDRYRSVQQPLRYLKYRTKTRASATILGAWFLSFL--WVIPILGWNHFMQQTS-V
RREDKCETDFYDVTWFKVMTAIINFYLPTLLMLWFYAKIYKAVRQHCQHRELINRSLPSF
SEIKLRPENPKGDAKKPGKESPWEVLKRKPKDAGGGSVLKSPSQTPKEMKSPVVFSQEDD
REVDKLYCFPLDIVHMQAAAEGSSRDYVAVNRSHGQLKTDEQGLNTHGASEISEDQMLGD
SQSFSRTDSDTTTETAPGKGKLRSGSNTGLDYIKFTWKRLRSHSRQYVSGLHMNRERKAA
KQLGFIMAAFILCWIPYFIFFMVIAFC-KNCCNEHLHMFTIWLGYINSTLNPLIYPLCNE
NFKKTFKRILHIRS----------------------------------------------
------*

>P1;HHR2
sequence:HHR2:1    : :*: ::::
-MAPNGTASSFCLDSTAC-----------KITITVVLAVLILITVAGNVVVCLAVGLNRR
LRNLTNCFIVSLAITDLLLGLLVLPFSAIYQLSCKWSFGKVFCNIYTSLDVMLCTASILN
LFMISLDRYCAVMDPLRYPVLVTPVRVAISLVLIWVISITLSFLSIHLGWNSRNETSKGN
HTTSKCKVQVN--EVYGLVDGLVTFYLPLLIMCITYYRIFKVARDQAKRI----------
-----------------NHISS--------------------------------------
------------------------------------------------------------
------------------------------------WKA------------ATIREHKAT
VTLAAVMGAFIICWFPYFTAFVYRGLRGDDAINEVLEAIVLWLGYANSALNPILYAALNR
DFRTGYQQLFCCRLANRNSHKTSLRSNASQLSRTQSREPRQQEEKPLKLQVWSGTEVTAP
QGATDR*


