>P1;4run
structureX:4run:8:A:154:A::::
EDITGTWYVKAMVVDKDFPEDRRPRKVSPVKVTALGGGNLEATFTFMREDR
CIQKKILMRKTEEPGKFSAYGGRKLIYLQELPGTDDYVFYSKDQRRGGLRY
MGNLVGRNPNTNLEALEEFKKLVQHKGLSEEDIFMPLQTGSCVLE*
>P1;Q9NPH6
sequence:Q9NPH6:1    : :*: ::::
EDITGTWYVKAMVVDKDFPEDRRPRKVSPVKVTALGGGKLEATFTFMREDR
CIQKKILMRKTEEPGKYSAYGGRKLMYLQELPRRDHYIFYCKDQHHGGLLH
MGKLVGRNSDTNREALEEFKKLVQRKGLSEEDIFTPLQTGSCVPE*